Parameters:
  StageName:
    Default: "${self:custom.stageName}"
    Description: The name of the current stage
    Type: String

Resources:
  ForwarderMappingTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: forwardingEmail
          AttributeType: S
        - AttributeName: destinationEmail
          AttributeType: S
      KeySchema:
        - AttributeName: forwardingEmail
          KeyType: HASH
        - AttributeName: destinationEmail
          KeyType: RANGE

  ForwarderS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: 30
            Id: delete-after-30-days
            Status: Enabled
  ForwarderS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: ForwarderS3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: GiveSESPermissionToWriteEmail
            Effect: Allow
            Principal:
              Service: "ses.amazonaws.com"
            Action: s3:PutObject
            Resource:
              Fn::Join: ["/", [Fn::GetAtt: [ForwarderS3Bucket, Arn], "*"]]
            Condition:
              StringEquals:
                aws:Referer:
                  Ref: AWS::AccountId
Outputs:
  ForwarderS3BucketArn:
    Value:
      Fn::GetAtt: [ForwarderS3Bucket, Arn]
    Description: ARN of S3 bucket for the forwarding email content

  ForwarderS3BucketName:
    Value:
      Ref: ForwarderS3Bucket
    Description: Name of S3 bucket for the forwarding email content
