iamRoleStatements:
  - Effect: "Allow"
    Action:
      - sns:Publish
    Resource:
      - "arn:aws:sns:*:*:${self:custom.stageName}-mailer-bounce"
      - "arn:aws:sns:*:*:${self:custom.stageName}-mailer"
  - Effect: Allow
    Action:
      - dynamodb:PutItem
      - dynamodb:GetItem
      - dynamodb:Query
    Resource:
      - Fn::GetAtt: [ LambdaMailerTable, Arn ]
      - Fn::Join: ["/", [ Fn::GetAtt: [LambdaMailerTable, Arn], "index", "*"]]
  - Effect: Allow
    Action:
      - ses:SendEmail
      - ses:SendRawEmail
    Resource:
      - "*"

  - Effect: Allow
    Action:
      - sqs:SendMessageBatch
      - sqs:SendMessage
    Resource:
      - Fn::ImportValue: "${self:custom.stageName}-dead-letter-queue-arn"
  - Effect: Allow
    Action:
      - s3:GetObject
    Resource:
      - Fn::Join: ["/", [Fn::GetAtt: [ForwarderS3Bucket, Arn], "*"]]
      - Fn::GetAtt: [ForwarderS3Bucket, Arn]
  - Effect: Allow
    Action:
      - s3:PutObject
      - s3:GetObject
    Resource:
      - Fn::Join: ["/", [Fn::GetAtt: [MailerAttachments, Arn], "*"]]
      - Fn::GetAtt: [MailerAttachments, Arn]

environment:
  STAGE_NAME: ${self:custom.stageName}
  LOG_LEVEL: DEBUG
  APP_NAME: ${self:service}
  ATTACHMENT_BUCKET:
    Ref: MailerAttachments

  # The error topic is part of the bootstrap infrastructure for uServerless

custom:
  stageName: ${opt:stage, self:provider.stage}
