iamRoleStatements:
  - Effect: "Allow"
    Action:
      - sns:Publish
    Resource:
      - "arn:aws:sns:*:*:${self:custom.stageName}-mailer-bounce"
      - "arn:aws:sns:*:*:${self:custom.stageName}-bounce-topic"
      - "arn:aws:sns:*:*:${self:custom.stageName}-mailer"
      - Fn::ImportValue: "${self:custom.stageName}-error-topic-arn"
  - Effect: Allow
    Action:
      - dynamodb:PutItem
      - dynamodb:GetItem
      - dynamodb:Query
    Resource:
      - Fn::GetAtt: [ DynamoDBTable, Arn ]
      - Fn::Join: ["/", [ Fn::GetAtt: [DynamoDBTable, Arn], "index", "*"]]
  - Effect: Allow
    Action:
      - ses:SendEmail
      - ses:SendRawEmail
    Resource:
      - "*"

  - Effect: Allow
    Action:
      - sqs:SendMessageBatch
      - sqs:SendMessage
    Resource:
      - Fn::ImportValue: "${self:custom.stageName}-dead-letter-queue-arn"
  - Effect: Allow
    Action:
      - s3:GetObject
    Resource:
      - Fn::Join: ["/", [Fn::GetAtt: [ForwarderS3Bucket, Arn], "*"]]
      - Fn::GetAtt: [ForwarderS3Bucket, Arn]

environment:
  SNS_ERROR_TOPIC:
    Fn::ImportValue: "${self:custom.stageName}-error-topic-arn"

custom:
  stageName: ${opt:stage, self:provider.stage}

deadLetterQueue:
  Fn::ImportValue: "${self:custom.stageName}-dead-letter-queue-arn"
