Parameters:
  TableName:
    Type: String
    Default: LambdaMailerSESNotifications
    Description: The name of the dynamodb table
  PartitionKey:
    Type: String
    Default: MessageId
    Description: The name of the main parition key
  SortKey:
    Type: String
    Default: SnsPublishTime
    Description: The name of the primary sort key
  SecondaryIndex:
    Type: String
    Default: DestinationAddress
    Description: The name of the secondary index
  ReadCapacityUnits:
    Default: 1
    Description: Dynamo read capacity units
    Type: Number
  WriteCapacityUnits:
    Default: 1
    Description: Dynamo write capacity units
    Type: Number
  StageName:
    Default: "${self:custom.stageName}"
    Description: The name of the current stage
    Type: String

Resources:

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
        Ref: TableName

      AttributeDefinitions:
      - AttributeName:
          Ref: PartitionKey
        AttributeType: S
      - AttributeName:
          Ref: SortKey
        AttributeType: S
      - AttributeName:
          Ref: SecondaryIndex
        AttributeType: S

      KeySchema:
      - AttributeName:
          Ref: PartitionKey
        KeyType: HASH
      - AttributeName:
          Ref: SortKey
        KeyType: RANGE

      GlobalSecondaryIndexes:
      - IndexName: EmailIndex
        KeySchema:
        - AttributeName:
            Ref: SecondaryIndex
          KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

      ProvisionedThroughput:
        ReadCapacityUnits:
          Ref: ReadCapacityUnits
        WriteCapacityUnits:
          Ref: WriteCapacityUnits

      TimeToLiveSpecification:
        AttributeName: ExpirationTime
        Enabled: true

  ForwarderS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: 30
            Id: delete-after-30-days
            Status: Enabled
  ForwarderS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: ForwarderS3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: GiveSESPermissionToWriteEmail
            Effect: Allow
            Principal:
              Service: "ses.amazonaws.com"
            Action: s3:PutObject
            Resource:
              Fn::Join: ["/", [Fn::GetAtt: [ForwarderS3Bucket, Arn], "*"]]
            Condition:
              StringEquals:
                aws:Referer:
                  Ref: AWS::AccountId


Outputs:
  EmailBounceAndComplaintTable:
    Value:
      Ref: DynamoDBTable

  ForwarderS3BucketArn:
    Value:
      Fn::GetAtt: [ForwarderS3Bucket, Arn]
    Description: Name of S3 bucket to hold website content

  ForwarderS3BucketName:
    Value:
      Ref: ForwarderS3Bucket
    Description: Name of S3 bucket to hold website content
