Parameters:
  StageName:
    Default: "${self:custom.stageName}"
    Description: The name of the current stage
    Type: String

Resources:
  ForwarderMappingTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: forwardingEmail
          AttributeType: S
        - AttributeName: destinationEmail
          AttributeType: S
      KeySchema:
        - AttributeName: forwardingEmail
          KeyType: HASH
        - AttributeName: destinationEmail
          KeyType: RANGE

  LambdaMailerTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
      - AttributeName: messageId
        AttributeType: S
      - AttributeName: snsPublishTime
        AttributeType: S
      - AttributeName: destinationAddress
        AttributeType: S

      KeySchema:
      - AttributeName: messageId
        KeyType: HASH
      - AttributeName: snsPublishTime
        KeyType: RANGE

      GlobalSecondaryIndexes:
      - IndexName: EmailIndex
        KeySchema:
        - AttributeName: destinationAddress
          KeyType: HASH
        Projection:
          ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  MailerAttachments:
    Type: AWS::S3::Bucket
    Properties:
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: 30
            Id: delete-after-30-days
            Status: Enabled
  ForwarderS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: 30
            Id: delete-after-30-days
            Status: Enabled
  ForwarderS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: ForwarderS3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: GiveSESPermissionToWriteEmail
            Effect: Allow
            Principal:
              Service: "ses.amazonaws.com"
            Action: s3:PutObject
            Resource:
              Fn::Join: ["/", [Fn::GetAtt: [ForwarderS3Bucket, Arn], "*"]]
            Condition:
              StringEquals:
                aws:Referer:
                  Ref: AWS::AccountId
  CreateTestDBPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Policy for third arties to add files to the mailer attachments bucket
      Path: "/"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: "s3:PutObject"
            Resource:
              Fn::GetAtt: [MailerAttachments, Arn]


Outputs:
  LambdaMailerTopicArn:
    Value:
      Fn::Join: [":", ["arn:aws:sns", Ref: "AWS::Region", Ref: "AWS::AccountId", "${self:custom.stageName}-mailer"]]
    Export:
      Name:
        Fn::Join: ["-", [Ref: StageName, "lambda-mailer-topic-arn"]]

  LambdaMailerBounceTopicArn:
    Value:
      Fn::Join: [":", ["arn:aws:sns", Ref: "AWS::Region", Ref: "AWS::AccountId", "${self:custom.stageName}-mailer-bounce"]]
    Export:
      Name:
        Fn::Join: ["-", [Ref: StageName, "lambda-mailer-bounce-topic-arn"]]

  EmailBounceAndComplaintTable:
    Value:
      Ref: LambdaMailerTable

  MailerAttachmentsS3BucketArn:
    Value:
      Fn::GetAtt: [MailerAttachments, Arn]
    Description: ARN of S3 bucket for storing mailer attachments

  MailerAttachmentsS3BucketName:
    Value:
      Ref: MailerAttachments
    Description: Name of S3 bucket for storing mailer attachments

  ForwarderS3BucketArn:
    Value:
      Fn::GetAtt: [ForwarderS3Bucket, Arn]
    Description: ARN of S3 bucket for the forwarding email content

  ForwarderS3BucketName:
    Value:
      Ref: ForwarderS3Bucket
    Description: Name of S3 bucket for the forwarding email content
